name: flutter_app
description: A Flutter app for AI Affiliate SaaS
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.18.0

flutter:
  uses-material-design: true
